config/routes.rb
Rails.application.routes.draw do
  root to: 'flats#index'
  resources :flats
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
  validates :name, :address, :description, :price_per_night, :number_of_guests, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :set_flat, only: [:show, :edit, :update, :destroy]

  def index
    if params[:query].present?
      @query = params[:query]
      @flats = Flat.where('name LIKE ?', "%#{params[:query]}%")
    else
      @flats = Flat.all
    end
  end

  def show
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    if @flat.save
      redirect_to flat_path(@flat)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @flat.update(flat_params)
      redirect_to flat_path(@flat)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @flat.destroy
    redirect_to flats_path
  end

  private

  def set_flat
    @flat = Flat.find(params[:id])
  end

  def flat_params
    params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/_form.html.erb
<div class='container default-card'>
  <%= simple_form_for (@flat) do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :description %>
    <%= f.input :price_per_night %>
    <%= f.input :number_of_guests %>
    <%= f.button :submit, class:'mt-3' %>
  <% end %>
</div>

app/views/flats/edit.html.erb
<h1>Edit This flat</h1>
<%= render 'form' %>
<%= link_to "Back to Flat", flat_path, class: 'btn btn-outline-primary' %>

app/views/flats/index.html.erb
<div class="container">
  <h1>All Our Flats</h1>

  <div class="row">
    <% if @query %>
      <p>You searched for <strong><%= @query %></strong>. We found <%= @flats.count %> result(s).</p>
    <% else %>
      <p>All <%= Flat.count %> flats.</p>
    <% end %>
  </div>

  <div class="row">
    <% @flats.each do |flat| %>
        <div class="col-sm-4">
          <div class="card mb-3" style='width: 20rem; height:25rem'>
            <img src="<%= flat.picture_url %>" class='card-img-top' alt="a beatiful room">
            <div class="card-body">
              <h4 class="card-title"><%= flat.name %></h5>
              <h6 class="card-subtitle"><%= flat.address %></h6>
              <h6 class='card-text'><i class="fa-solid fa-people-roof"></i>   <%= flat.number_of_guests %>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <i class="fa-solid fa-brazilian-real-sign"></i>   <%= flat.price_per_night %></p>
              </h6>
              <%= link_to "More Info", flat_path(flat), class: 'btn btn-primary' %>
              <%= link_to 'Edit', edit_flat_path(flat), class: 'btn btn-success' %>
              <%= link_to 'Delete', flat_path(flat), method: :delete, data: {confirm: "Are you sure?"}, class: 'btn btn-danger' %>
            </div>
          </div>
        </div>
    <% end %>
  </div>
</div>

app/views/flats/new.html.erb
<h1>Add a New Flat</h1>
<%= render 'form' %>

app/views/flats/show.html.erb
<div class='top-background-image' style="background-image: url('<%= @flat.picture_url %>')">
</div>

<div class='container' style='margin-top: -75px'>
  <div class="row">
    <div class="col-8">
      <div class='default-card'>
        <h1><%= @flat.name %></h1>
        <p><%=  @flat.address %></p>
      </div>
      <div class='default-card'>
        <h3>A bit more about this place...</h3>
        <p><%= @flat.description %></p>
        <div style="background-image: url('https://maps.googleapis.com/maps/api/staticmap?center=<%= @flat.address %>&zoom=13&scale=2&size=1000x1000&maptype=roadmap&markers=color:red%7C<%= @flat.address %>&key=AIzaSyAPpx0wk4d-AQ8bhe8-a-ihC7NXLoPElhg"></div>
      </div>
    </div>

    <div class="col-4">
      <div class='default-card'>
        <form action="">
          <div class="input-group">
            <span class="input-group-text" id="basic-addon1">From:</span>
            <input type="text" class='form-control' placeholder='01/01/2022' aria-label="Username" aria-describedby="basic-addon1">
          </div>
          <div class="input-group mt-2">
            <span class="input-group-text" id="basic-addon1">To:</span>
            <input type="text" class="form-control" placeholder="18/10/2017" aria-label="Username" aria-describedby="basic-addon1">
          </div>
          <input type="submit" value="Book" class="btn btn-success mt-2" style="width: 100%">
        </form>
      </div>
      <div class='default-card'>
        <h3>Details</h3>
        <p><i class="fa-solid fa-people-roof"></i> <%= @flat.number_of_guests %> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <i class="fa-solid fa-brazilian-real-sign"></i> <%= @flat.price_per_night %></p>
      </div>

      <div class='default-card'>
        <span style='font-size: 1.5rem'>Share</span>&nbsp;&nbsp;&nbsp;&nbsp;
        <i class="fa-brands fa-facebook-square me-2"></i>
        <i class="fa-brands fa-twitter-square me-2"></i>
        <i class="fa-brands fa-pinterest-square me-2"></i>
      </div>
    </div>
  </div>

<%= link_to "Edit Flat", edit_flat_path(@flat), class: 'btn btn-primary' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.1/css/all.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    
      <%= yield %>
    
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light sticky-top">
  <div class="container-fluid">
    <%= link_to "Simple Airbnb", root_path, class: "navbar-brand" %>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <div class="ms-auto d-inline-flex">
        <form class="d-inline-flex my-2 my-lg-0">
          <input class="form-control me-2" name="query" type="search" placeholder="Search" aria-label="Search" value="<%= params[:query] %>">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
        <%= link_to "Add Flat", new_flat_path, class: "btn btn-outline-primary my-2 my-sm-0 ms-2" %>
      </div>
    </div>
  </div>
</nav>